import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header.js";
import Footer from "@/components/footer";

export const metadata = {
  title: "혹성의 아이",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <Header title={metadata.title} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
